// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Couple struct {
	ID        int64
	UserID    pgtype.Int8
	PartnerID pgtype.Int8
}

type User struct {
	ID       int64
	Name     string
	Username string
	Password []byte
}

type Wish struct {
	ID          int64
	Title       string
	Description pgtype.Text
	Url         pgtype.Text
	Price       pgtype.Text
	Completed   pgtype.Bool
	CoupleID    pgtype.Int8
	CreatedAt   pgtype.Timestamp
}
